# Generated by golem-hw-detect on 2026-09-08T19:30:48Z.
# The target machine's detected hardware — imported by the installer
# so Golem builds tuned for THIS box. Safe to regenerate.
{ ... }:
{
  golem.hardware = {
    cpuModel = "13th Gen Intel(R) Core(TM) i9-13905H";
    cores = 14;
    threads = 20;
    ramMB = 31816;
    gpu = "intel";
    intelLegacy = false;
    firmware = "uefi";
    nvidiaGen = "turing+";
    nvidiaBusId = "PCI:1:0:0";
    intelBusId = "PCI:0:2:0";
    gpu2 = "nvidia";
    gpu2BusAddr = "0000:01:00.0";
    gpu2Health = "working";
    panelDpi = 239;
    hasBluetooth = true;
    cpuVendor = "intel";
    chassis = "laptop";
  };
}
