# Generated by golem-hw-detect on 2009-01-01T00:00:24Z.
# The target machine's detected hardware — imported by the installer
# so Golem builds tuned for THIS box. Safe to regenerate.
{ ... }:
{
  golem.hardware = {
    cpuModel = "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz";
    cores = 2;
    threads = 4;
    ramMB = 7824;
    gpu = "nvidia";
    intelLegacy = true;
    firmware = "uefi";
    nvidiaGen = "unknown";
    nvidiaBusId = "PCI:4:0:0";
    intelBusId = "PCI:0:2:0";
    panelDpi = 102;
    hasBluetooth = false;
    cpuVendor = "intel";
    chassis = "laptop";
  };
}
