# Generated by golem-hw-detect on 2026-09-11T09:20:16Z.
# The target machine's detected hardware — imported by the installer
# so Golem builds tuned for THIS box. Safe to regenerate.
{ ... }:
{
  golem.hardware = {
    cpuModel = "AMD Ryzen 7 4700U with Radeon Graphics";
    cores = 8;
    threads = 8;
    ramMB = 7159;
    gpu = "amd";
    intelLegacy = false;
    firmware = "uefi";
    panelDpi = 143;
    hasBluetooth = true;
    cpuVendor = "amd";
    chassis = "laptop";
  };
}
