# Generated by golem-hw-detect on 2026-09-11T13:18:17Z.
# The target machine's detected hardware — imported by the installer
# so Golem builds tuned for THIS box. Safe to regenerate.
{ ... }:
{
  golem.hardware = {
    cpuModel = "Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz";
    cores = 2;
    threads = 4;
    ramMB = 3718;
    gpu = "intel";
    intelLegacy = true;
    firmware = "bios";
    gpu2 = "amd";
    gpu2BusAddr = "0000:01:00.0";
    gpu2Health = "failing";
    hasBluetooth = true;
    cpuVendor = "intel";
    chassis = "laptop";
  };
}
