# Generated by golem-hw-detect on 2026-09-04T12:43:24Z.
# The target machine's detected hardware — imported by the installer
# so Golem builds tuned for THIS box. Safe to regenerate.
{ ... }:
{
  golem.hardware = {
    cpuModel = "13th Gen Intel(R) Core(TM) i9-13905H";
    cores = 4;
    threads = 4;
    ramMB = 3917;
    gpu = "virtio";
    intelLegacy = false;
    vmGuest = "qemu";
    hasBluetooth = false;
    cpuVendor = "intel";
    chassis = "unknown";
  };
}
