# Generated by waverunner-apply from packages.list. Do not edit by hand.
{ pkgs, ... }:
{
  home.packages = with pkgs; [
    android-studio
    blueman
    bluez
    brightnessctl
    btop
    firefox
    fzf
    inkscape
    localsend
    obs-studio
    sfizz
    thunar
    vlc
  ];
}
