# Generated by golem-hw-detect on 2026-09-04T04:43:18Z; the cpu block was
# re-derived 2026-09-05 from this fixture's own cpuinfo.txt when the probe
# learned to tell cores from threads (it used to report nproc as "cores",
# so this machine's 2-core i5-5200U read as 4). Detection is a pure
# function of evidence, so deriving it from the committed dump is the same
# answer the machine would give — re-confirm on its next boot anyway.
# The target machine's detected hardware — imported by the installer
# so Golem builds tuned for THIS box. Safe to regenerate.
{ ... }:
{
  golem.hardware = {
    cpuModel = "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz";
    cores = 2;
    threads = 4;
    ramMB = 3833;
    gpu = "intel";
    intelLegacy = false;
    panelDpi = 102;
    hasBluetooth = true;
    cpuVendor = "intel";
    chassis = "laptop";
  };
}
