# golem-hw-detect — read this machine's hardware and emit the Nix that
# tunes Golem for it. The S9 installer runs this on the TARGET, before the
# first build, so first boot comes up correctly sized and with the right GPU
# driver (see system/hardware.nix for what the emitted options drive).
#
#   golem-hw-detect            # print golem-hardware.nix to stdout
#   golem-hw-detect -o DIR     # write DIR/golem-hardware.nix and, via
#                              # nixos-generate-config, DIR/hardware-configuration.nix
#
# Pure read-only detection except for the files it is asked to write. Safe
# to run on a live machine to preview what the installer would generate.
{ pkgs, ... }:

{
  environment.systemPackages = [
    (pkgs.writeShellApplication {
      name = "golem-hw-detect";
      runtimeInputs = [ pkgs.coreutils pkgs.gnugrep pkgs.nixos-install-tools ];
      text = ''
        outdir=""
        if [[ "''${1:-}" == "-o" && -n "''${2:-}" ]]; then
          outdir="$2"
        fi

        # ── RAM (MiB) and cores ──────────────────────────────────────────
        ram_kb=$(grep -m1 MemTotal /proc/meminfo | grep -oE '[0-9]+')
        ram_mb=$(( ram_kb / 1024 ))
        cores=$(nproc)

        # ── GPU vendor, from the PCI vendor id of each DRM card ───────────
        # Priority nvidia > amd > intel > virtio: on a hybrid laptop the
        # discrete nvidia is the one that needs the non-default driver, and
        # a machine with both an iGPU and a dGPU should pick the dGPU here.
        gpu="auto"
        have_intel=0
        intel_legacy=false
        for v in /sys/class/drm/card[0-9]*/device/vendor; do
          [[ -r "$v" ]] || continue
          id=$(tr -d '[:space:]' < "$v")
          case "$id" in
            0x10de) gpu="nvidia" ;;
            0x1002) [[ "$gpu" == "nvidia" ]] || gpu="amd" ;;
            0x8086)
              have_intel=1
              # Pre-Skylake Intel iGPUs (Haswell/Ivy Bridge and older, PCI
              # device id < 0x1600) need the LEGACY i965 VA-API driver — iHD
              # (intel-media-driver) only supports Broadwell+ and silently
              # gives no hardware decode on older parts, which is exactly why a
              # 2013 HD 5000 CPU-decodes VP9 and cooks the chip. Skylake+
              # (>= 0x1900) and Broadwell (0x16xx) are fine on iHD.
              dev=$(tr -d '[:space:]' < "$(dirname "$v")/device" 2>/dev/null || true)
              if [[ -n "$dev" ]] && (( dev < 0x1600 )); then intel_legacy=true; fi
              ;;
            0x1af4|0x1234|0x15ad) [[ "$gpu" == "auto" ]] && gpu="virtio" ;;
          esac
        done
        if [[ "$gpu" == "auto" && "$have_intel" == 1 ]]; then
          gpu="intel"
        fi

        # ── Emit ─────────────────────────────────────────────────────────
        gen() {
          cat <<EOF
        # Generated by golem-hw-detect on $(date -u +%Y-%m-%dT%H:%M:%SZ).
        # The target machine's detected hardware — imported by the installer
        # so Golem builds tuned for THIS box. Safe to regenerate.
        { ... }:
        {
          golem.hardware = {
            ramMB = $ram_mb;
            cores = $cores;
            gpu = "$gpu";
            intelLegacy = $intel_legacy;
          };
        }
        EOF
        }

        if [[ -n "$outdir" ]]; then
          mkdir -p "$outdir"
          gen > "$outdir/golem-hardware.nix"
          echo "wrote $outdir/golem-hardware.nix (ramMB=$ram_mb cores=$cores gpu=$gpu)" >&2
          # The rest of the machine's hardware (filesystems, kernel modules,
          # microcode) is nixos-generate-config's job — the installer folds
          # both files into the flake it builds.
          nixos-generate-config --no-filesystems --dir "$outdir" 2>/dev/null \
            && echo "wrote $outdir/hardware-configuration.nix" >&2 \
            || echo "note: nixos-generate-config skipped (needs root / a target root)" >&2
        else
          gen
        fi
      '';
    })
  ];
}
