# Privileged apply helper for waverunner's declarative installs — flake port.
#
# SECURITY MODEL (unchanged from the channel version)
# ---------------------------------------------------
# The ONLY user-writable surface is the DATA file
#   ~<user>/.config/waverunner/packages.list   (one nixpkgs attr per line)
# This script (root) PARSES that file as data — it never `import`s it — and
# strictly validates every line against ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ before
# emitting the real Nix. The generated file is root-owned; nothing but this
# service writes it.
#
# FLAKE TWIST: the generated waverunner-packages.nix lives INSIDE the flake
# checkout (system/home/) — flakes can't read outside their tree — and must
# be git-tracked or the build won't see it, so the script `git add`s it.
# Rebuilds run `nixos-rebuild switch --flake <flakeDir>#golem`.
#
# TRIGGER: a systemd.path watches packages.list; writing it runs this once.
# FEEDBACK: result is written to apply-status.json (chowned back to the user).
# ATOMIC: a failed switch never activates; last-good is restored so the tree
# always stays buildable.
#
# (The channel version also carried system.autoUpgrade — dropped here: on a
# flake system "upgrade" = bump flake inputs + rebuild, a deliberate act.
# The Golem upgrade story is an open S7 design item.)

{ config, pkgs, lib, ... }:

let
  flakeDir = config.golem.flakeDir;
  flakeAttr = config.golem.flakeAttr;
  user = "max";
  userHome = "/home/${user}";
  listFile = "${userHome}/.config/waverunner/packages.list";
  statusFile = "${userHome}/.config/waverunner/apply-status.json";
  generated = "${flakeDir}/system/home/waverunner-packages.nix";

  applyScript = pkgs.writeShellApplication {
    name = "waverunner-apply";
    # This script does its own error handling (it must always write a status
    # and restore the last-good file on a failed rebuild), so drop the
    # default `errexit` — keep nounset + pipefail.
    bashOptions = [ "nounset" "pipefail" ];
    runtimeInputs = [
      config.system.build.nixos-rebuild
      config.nix.package
      pkgs.git
      pkgs.jq
      pkgs.coreutils
    ];
    text = ''
      list=${lib.escapeShellArg listFile}
      status=${lib.escapeShellArg statusFile}
      gen=${lib.escapeShellArg generated}
      flakedir=${lib.escapeShellArg flakeDir}
      lastgood="$gen.last-good"
      started=$(date +%s.%N)

      write_status() {
        # $1 phase ("building"|"done")   $2 ok (true|false|null)   $3 error (json string or null)
        tmp=$(mktemp)
        printf '{"phase":"%s","ok":%s,"started":%s,"finished":%s,"error":%s}\n' \
          "$1" "$2" "$started" "$(date +%s.%N)" "$3" > "$tmp"
        mv "$tmp" "$status"
        chown ${user}:users "$status" 2>/dev/null || true
        chmod 644 "$status" 2>/dev/null || true
      }

      write_status "building" null null

      # 1. Validate: keep only strict nixpkgs attr tokens; anything else is
      #    dropped (never interpreted).
      attrs=()
      if [[ -f "$list" ]]; then
        while IFS= read -r line || [[ -n "$line" ]]; do
          line="''${line%%#*}"
          line="$(printf '%s' "$line" | tr -d '[:space:]')"
          if [[ -z "$line" ]]; then
            continue
          fi
          if [[ "$line" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ ]]; then
            attrs+=("$line")
          else
            echo "waverunner-apply: rejected invalid entry: $line" >&2
          fi
        done < "$list"
      fi

      # 2. Generate the root-owned Nix from the validated tokens, and make
      #    sure the flake can see it (tracked file; dirty is fine).
      {
        echo "# Generated by waverunner-apply from packages.list. Do not edit by hand."
        echo "{ pkgs, ... }:"
        echo "{"
        echo "  home.packages = with pkgs; ["
        for a in ''${attrs[@]+"''${attrs[@]}"}; do
          echo "    $a"
        done
        echo "  ];"
        echo "}"
      } > "$gen.new"
      mv "$gen.new" "$gen"
      # Root inside the user's checkout: /etc/gitconfig carries the
      # safe.directory entry (configuration.nix) for git AND nix's libgit2.
      git -C "$flakedir" add system/home/waverunner-packages.nix || true

      # 3. Rebuild. On success snapshot last-good; on failure restore it so
      #    the next rebuild is never poisoned by a bad add.
      if err=$(nixos-rebuild switch --flake "$flakedir#${flakeAttr}" 2>&1); then
        cp -f "$gen" "$lastgood"
        write_status "done" true null
      else
        if [[ -f "$lastgood" ]]; then
          cp -f "$lastgood" "$gen"
          git -C "$flakedir" add system/home/waverunner-packages.nix || true
        fi
        errjson=$(printf '%s' "$err" | tail -c 4000 | jq -Rs .)
        write_status "done" false "$errjson"
        echo "$err" >&2
        exit 1
      fi
    '';
  };
in
{
  config = lib.mkIf (flakeDir != null) {
    systemd.services.waverunner-apply = {
      description = "Apply waverunner's declarative package list (nixos-rebuild switch --flake)";
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${applyScript}/bin/waverunner-apply";
      };
    };

    systemd.paths.waverunner-apply = {
      description = "Watch waverunner's packages.list for changes";
      wantedBy = [ "multi-user.target" ];
      pathConfig = {
        PathChanged = listFile;
        Unit = "waverunner-apply.service";
      };
    };
  };
}
