# Generated by golem-hw-detect on 2026-09-11T12:59:30Z.
# The target machine's detected hardware — imported by the installer
# so Golem builds tuned for THIS box. Safe to regenerate.
{ ... }:
{
  golem.hardware = {
    cpuModel = "Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz";
    cores = 2;
    threads = 4;
    ramMB = 3858;
    gpu = "intel";
    intelLegacy = true;
    firmware = "uefi";
    broadcomWifi = true;
    panelDpi = 126;
    hasBluetooth = true;
    cpuVendor = "intel";
    chassis = "laptop";
  };
}
